set -g prefix C-a
setw -g mode-keys vi
unbind C-b
bind-key C-a send-prefix
unbind r
bind r source-file ~/.tmux.conf
bind k run-shell "~/scripts/tmux_sessionizer.sh"

set-option -g allow-passthrough on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '5'

setw -g mouse on

#Variables
HALF_ROUND_OPEN="#(printf '\uE0B6')"
HALF_ROUND_CLOSE="#(printf '\uE0B4')"
TRIANGLE_OPEN="#(printf '\uE0B2')"
TRIANGLE_CLOSE="#(printf '\uE0B0')"

#Styling
set-option -g status-position bottom 

set-option -g status-style bg=#504945,fg=#fbf1c7

set-option -g status-left "\
#[bg=#fabd2f,fg=#282828] #S \
#[fg=#fabd2f,bg=default]${TRIANGLE_CLOSE}\
"

set-option -g status-left-length 100

set-option -g status-right "\
#[fg=#d3869b,bg=default]${TRIANGLE_OPEN}\
#[bg=#d3869b,fg=#282828] #h \
%I:%M%p\
 \
"

set-option -g status-right-length 100

set-option -g window-status-format "\
 \
#I\
#[fg=default]:\
#[fg=default]#W\
 \
"
set-option -g window-status-current-format "\
#[fg=#83a598,bg=default]${HALF_ROUND_OPEN}\
#[bg=#83a598,fg=default]#I\
#[fg=default]:\
#[fg=default]#W\
#[fg=#83a598,bg=default]${HALF_ROUND_CLOSE}\
"

set-option -g status-justify absolute-centre

set-option -g window-status-separator ""

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm'
run-shell ~/clone/path/continuum.tmux
