foreground              #c5cdd9
background              #152528
selection_foreground    #1b1d29
selection_background    #c5cdd9
cursor                 #ebebeb
cursor_text_color      #1b1d29
background_opacity 0.6

color0  #393b44
color1  #c94f6d
color2  #81b29a
color3  #dbc074
color4  #719cd6
color5  #9d79d6
color6  #63cdcf
color7  #dfdfe0

color8  #575860
color9  #d6616b
color10 #58cd8b
color11 #ffe37e
color12 #84cee4
color13 #b4a4f7
color14 #79e6f3
color15 #ffffff
