format = """
$os\
$username\
[](bg:#c54e45 fg:#254147)\
$directory\
[](fg:#c54e45 bg:#934e69)\
$git_branch\
$git_status\
[](fg:#934e69 bg:#4d7d90)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#4d7d90 bg:#89aeb8)\
$docker_context\
[](fg:#89aeb8 bg:#688b89)\
$time\
[ ](fg:#688b89)\
"""

# Disable the blank line at the start of the prompt
add_newline = true

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#254147"
style_root = "bg:#254147"
format = '[ $user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#254147"
disabled = true # Disabled by default

[directory]
style = "bg:#c54e45"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#4d7d90"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#89aeb8"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#4d7d90"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#4d7d90"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#934e69"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#934e69"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = ""
style = "bg:#4d7d90"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#4d7d90"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = ""
style = "bg:#4d7d90"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = ""
style = "bg:#4d7d90"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = ""
style = "bg:#4d7d90"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#4d7d90"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥"
style = "bg:#4d7d90"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#4d7d90"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#4d7d90"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#688b89"
format = '[ $time ]($style)'
